---
title: "Spatial Analysis of School Shootings"
author: "J Steven Raquel"
date: "3/10/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(lubridate)
# spatial data libraries
library(sf)
library(sp)
library(spdep)
library(raster) 
library(maps)
library(maptools)
library(spatstat)

library(plotrix)
library(ggmap) # for utilizing Google Maps API 
library(splancs)
```

# Introduction

The issue of gun violence in the United States, particularly in schools, has been referred to as both an epidemic and a public health crisis. 


# Background

## Data

# Methods

# Discussion

# References

```{r read_incidents_old, eval = F}
incidents <- read_csv("ss_incidents.csv", na = c("", "null", "N/A"),
                      show_col_types = F)
# incident dataset filtered
incidents_f <- incidents %>%
  dplyr::select(Incident_ID, Reliability, Date, Quarter, School, 
                City, State, School_Level, Location, Location_Type, 
                During_School, Time_Period, Situation, 
                Bullied, Domestic_Violence, Gang_Related, 
                Preplanned, Shots_Fired) %>%
  mutate(Date = as.Date(Date)) %>%
  filter(!(Situation %in% c("Accidental", "Suicide/Attempted",
                            "Intentional Property Damage"))
         ) %>%
  filter(Gang_Related == "No") %>% 
  unite(Full_Location, c(School, City, State), remove = F, sep = " ") %>%
  mutate(Full_Location = as.character(Full_Location)) %>%
  filter(!(State %in% c("AK", "HI"))) %>%
  replace_na(list(Situation = "Unknown"))

incidents_f <- incidents_f %>% 
  mutate_at(setdiff(names(incidents_f), c("Incident_ID", "Full_Location", "Date")), 
               .funs = as.factor)
```

```{r get-lat-lon}
# using Google Maps API to search up the lat/lon of all the schools
#incidents_f2 <- incidents_f %>% 
#  mutate_geocode(Full_Location)
# write.csv(incidents_f2, "ss_incidents2.csv", row.names = F)
```


```{r reading_data, warnings = F}

# gun control laws 
# violent video game sales
# music
perps <- read_csv("ss_perps.csv", na = c("", "null", "N/A"), 
                  show_col_types = F)
weapons <- read_csv("ss_weapons.csv", na = c("", "null", "N/A"),
                    show_col_types = F)

gun_control <- read_csv("gun_control_database.csv", col_types = "cf")

# perpetrator dataset filtered
perps_f <- perps %>% 
  dplyr::select(incidentid, age, gender, race, schoolaffiliation) %>%
  rename(Incident_ID = incidentid, Age = age, Gender = gender, 
         Race = race, School_Affiliation = schoolaffiliation)

# weapon dataset filtered
weapons_f <- weapons %>%
  dplyr::select(incidentid, weapontype) %>%
  rename(Incident_ID = incidentid, Weapon_Type = weapontype)

# Youth Mental Healthcare Rankings
ymhc_2019 <- read_csv("youth_mhc_2019_2.csv", 
                        col_names = T, col_types = "ic") %>%
  rename(Youth_MHC_Rank = Rank, State_Name = State)
ymhc_2019$State <- state.abb[match(ymhc_2019$State_Name, state.name)]

incidents_f2 <- read_csv("ss_incidents2.csv", show_col_types =F)
# adding perpetrator information to the dataset
incidents_f3 <- left_join(incidents_f2, perps_f, by = "Incident_ID")
# adding weapon information to the dataset
incidents_f4 <- left_join(incidents_f3, weapons_f, by = "Incident_ID")


# data on shootings between 1970-2022
df <- incidents_f2

df_90_19 <- df %>% filter(Date >= "1990-01-1" & Date <= "2019-12-31")
df_90S <- df %>% filter(Date >= "1990-01-01" & Date <= "1999-12-31")
df_00S <- df %>% filter(Date >= "2000-01-01" & Date <= "2009-12-31")
df_10S <- df %>% filter(Date >= "2010-01-01" & Date <= "2019-12-31")

nrow(df_90S)
nrow(df_00S)
nrow(df_10S)

# major school shootings list:
# Columbine High School 1999
# Virginia Tech 2007
# Sandy Hook 2012
# Umpqua Community College 2015
# Santa Fe High School 2018
# Marjory Stoneman Douglas 2018

```

```{r sf-wrangling}
# sf is loaded
# CRS for albers is 5070
# default for us states is 4269
data(us_states)

sf_90_19 <- st_as_sf(df_90_19, coords = c("lon", "lat")) %>% 
  st_set_crs(4269)

sf_90S <- st_as_sf(df_90S, coords = c("lon", "lat")) %>%
  st_set_crs(4269)

sf_00S <- st_as_sf(df_00S, coords = c("lon", "lat")) %>%
  st_set_crs(4269)

sf_10S <- st_as_sf(df_10S, coords = c("lon", "lat")) %>% 
  st_set_crs(4269)

```

```{r cities-cleaning}
cities_df <- df %>% dplyr::select(City, State, lon, lat) %>% distinct()

# names of cities with more than one shooting from 1990-2022
cities_multi <- table(cities_df$City)%>% 
  as.data.frame() %>%
  rename(City = Var1) %>%
  filter(Freq > 1)
cities_multi_names <- cities_multi$City

# the distinct names and coordinates of cities with >1 shooting
cities_df2 <- cities_df %>% 
  unite(City_State, c(City, State), sep = ", ", remove = F) %>%
  filter(City %in% cities_multi_names) %>% 
  arrange(City_State) %>%
  distinct(City, .keep_all = T)

cities_sf <- st_as_sf(cities_df2, coords = c("lon", "lat")) %>%
  st_set_crs(4269) %>%
  mutate(x = purrr::map_dbl(geometry,1),
         y = purrr::map_dbl(geometry,2))
```

```{r plot-shootings-90s}
# looking at 3 decades of school shootings
ggplot() + 
  geom_sf(data = us_states) +
  geom_sf(data = sf_90S, size = 0.75, col = "red") + 
#  geom_sf(data = cities_sf, color = "black", size = 1) +
#  geom_text_repel(data = cities_sf, 
#                  aes(x = x, y = y, label = City_State),
#                  hjust = 1, vjust = -0.25, size = 2.5) +
  theme_minimal() + 
  theme(axis.title = element_blank()) +
  ggtitle("School Shootings in US, 1990s")
```

```{r plot-shooting-00s}
ggplot() + 
  geom_sf(data = us_states) +
  geom_sf(data = sf_00S, size = 0.75, col = "red") + 
#  geom_sf(data = cities_sf, color = "black", size = 1) +
#  geom_text_repel(data = cities_sf, 
#                  aes(x = x, y = y, label = City_State),
#                  hjust = 1, vjust = -0.25, size = 2.5) +
  theme_minimal() + 
  theme(axis.title = element_blank()) +
  ggtitle("School Shootings in US, 2000s")
```

```{r plot-shootings-2010s}
ggplot() + 
  geom_sf(data = us_states) +
  geom_sf(data = sf_10S, size = 0.75, col = "red") + 
#  geom_sf(data = cities_sf, color = "black", size = 1) +
#  geom_text_repel(data = cities_sf, 
#                  aes(x = x, y = y, label = City_State),
#                  hjust = 1, vjust = -0.25, size = 2.5) +
  theme_minimal() + 
  theme(axis.title = element_blank()) +
  ggtitle("School Shootings in US, 2010s")

```



```{r states-ppp}
# sf is loaded
# raster is loaded
# spatstat.geom is loaded
# tigris is loaded
# download US states shapefile

## Using the maps package in R which also contains a shapefile for the US
us_map <- map("usa",plot=F)
## These are the vectors with the longitudes and latitudes for the points in the boundary
us_boundaries_x <- us_map$x
range(us_boundaries_x,na.rm=T)
#[1] -124.68134  -67.00742
us_boundaries_y <- us_map$y
range(us_boundaries_y,na.rm=T)
#[1] 25.12993 49.38323

us_names <- us_map$names

plot(us_boundaries_x[1:6887],
  us_boundaries_y[1:6887],type="l",col="black",xlab="Longitude",ylab="Latitude")

## Creating the matrix with the longitude and latitude of the boundaries
us_poly <- matrix(cbind(us_boundaries_x[1:6886],us_boundaries_y[1:6886]),
                        nrow=6886,ncol=2)
## Creating the window of the spatial point pattern.
us_win <- owin(poly=us_poly)



matrix_90_19 <- matrix(cbind(df_90_19$lon, df_90_19$lat),
                     nrow = length(df_90_19$lat), ncol = 2)
matrix_90s <- matrix(cbind(df_90S$lon,df_90S$lat), 
                     nrow = length(df_90S$lat), ncol = 2)
matrix_00s <- matrix(cbind(df_00S$lon, df_00S$lat),
                     nrow = length(df_00S$lat), ncol = 2)
matrix_10s <- matrix(cbind(df_10S$lon, df_10S$lat), 
                     nrow = length(df_10S$lat), ncol = 2)
## Creating the ppp oject: some shootings are outside the boundaries (8). You
## might look at them one by one.

ppp_90_19 <- as.ppp(matrix_90_19, us_win)
ppp_90s <- as.ppp(matrix_90s, us_win)
ppp_00s <- as.ppp(matrix_00s, us_win)
ppp_10s <- as.ppp(matrix_10s, us_win)

# creating ppp object
plot(ppp_90s, axes = T)
plot(ppp_00s, axes = T)
plot(ppp_10s, axes = T)
```


```{R KL-functions, cache = T}

# 1990s
K_90s <- Kest(ppp_90s)
L_90s <- Lest(ppp_90s)

# 2010s
K_00s <- Kest(ppp_00s)
L_00s <- Lest(ppp_00s)

# 2020s
K_10s <- Kest(ppp_10s)
L_10s <- Lest(ppp_10s)

```

```{R envelopes, eval = F}
# envelopes
#env_K <- envelope(X_ppp, fun = Kest, nsim = 99)
#env_L <- envelope(X_ppp, fun = Lest, nsim = 99)
```


```{r plot-K-function}
plot(K_90s, main = "K function of School Shootings, 1990s")
plot(L_90s, main = "L function of US School Shootings, 1990s")
```
```{r quadrat-test}
# Monte Carlo
# Ha: the PP is clustered
quadrat.test(ppp_90s, alternative = "clustered",
             method = "MonteCarlo", nsim = 4999, conditional = T)

quadrat.test(ppp_00s, alternative = "clustered",
             method = "MonteCarlo", nsim = 4999, conditional = T)

quadrat.test(ppp_10s, alternative = "clustered",
             method = "MonteCarlo", nsim = 4999, conditional = T)
```

```{r bandwidth-calculate}
# optimal bandwidth for the kernel density of each point pattern
bw_opt_90_19 <- bw.diggle(ppp_90_19)
bw_opt_90s <- bw.diggle(ppp_90s) 
bw_opt_00s <- bw.diggle(ppp_00s) 
bw_opt_10s <- bw.diggle(ppp_10s) 
```


```{r density-90s}
# cross-validated bandwidth selection for finding optimal bandwidth

dens_90s <- density(ppp_90s, bw = bw_opt)
plot(dens_90s, main = "Density of School Shootings, 1990-1999")
```
```{r density-00s}

dens_00s <- density(ppp_00s, bw = bw_opt)
plot(dens_00s, main = "Density of School Shootings, 2000-2009")
```

```{r density-10s}

dens_10s <- density(ppp_10s, bw = bw_opt)
plot(dens_10s, main = "Density of School Shootings, 2010-2019")
```

```{r log-gaussian-cox}
logcp <- lgcp.estK(X_ppp, c(sigma2 = 10, alpha = 2))
plot(logcp,
     main = "Fitted K function and theoretical K function \n log Gaussian-Cox process")
```

